name: CI

env:
  NODE_VERSION: lts/*
  BUN_VERSION: latest

on:
  schedule:
    - cron: "0 9 * * *"
  push:
  pull_request:

jobs:
  build-examples:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - run: bun i --frozen-lockfile
      - run: bun run build

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: bun i --frozen-lockfile
      - run: bun run test

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - run: bun i --frozen-lockfile
      - run: bun run lint

  jsr-publish-dry-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - run: bun i --frozen-lockfile
      - run: bun run publish:jsr --dry-run
        working-directory: packages/unplugin-typia

  upload-pkg-pr-now:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - run: bun i --frozen-lockfile
      - run: |
          bun run prepublishOnly
          bunx pkg-pr-new publish
        working-directory: packages/unplugin-typia

  action-timeline:
    needs:
      - lint
      - test
      - build-examples
      - jsr-publish-dry-run
      - upload-pkg-pr-now
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2
