name: jsr

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: bun i --frozen-lockfile
      - run: bun run publish
        working-directory: packages/unplugin-typia
